name: Daily Hacking Tool Post

on:
  schedule:
    - cron: "0 6 * * *"  # Everyday 6 AM UTC = 11:30 AM IST
  workflow_dispatch:  # Manual run option

jobs:
  post-tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Random Tool
        run: |
          TOOLS=("https://github.com/sqlmapproject/sqlmap" \
                 "https://github.com/laramies/theHarvester" \
                 "https://github.com/maurosoria/dirsearch" \
                 "https://github.com/D4Vinci/Cr3dOv3r" \
                 "https://github.com/mishakorzik/EmailAllinator")

          RANDOM_TOOL=${TOOLS[$RANDOM % ${#TOOLS[@]}]}
          echo "TOOL=$RANDOM_TOOL" >> $GITHUB_ENV

      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🛠️ Daily Hacking Tool: $TOOL\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
